# Use an official Python runtime as a parent image
FROM python

# Set the working directory in the container
WORKDIR /

# Copy the current directory contents into the container at /app
COPY . /smart_dict

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r req.txt

# Make port 8000 available to the world outside this container
EXPOSE 9000

# Define environment variable
ENV NAME World

# Run your application
CMD ["python", "your_app.py"]
