# Generated by Django 5.0.6 on 2024-07-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('meaning', models.TextField()),
                ('pronunciation', models.TextField(blank=True, null=True)),
                ('sentence1', models.TextField(blank=True, null=True)),
                ('sentence2', models.TextField(blank=True, null=True)),
                ('sentence3', models.TextField(blank=True, null=True)),
                ('sentence4', models.TextField(blank=True, null=True)),
                ('sentence5', models.TextField(blank=True, null=True)),
                ('types', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('last_seen_date', models.DateField(auto_now=True)),
                ('learned', models.BooleanField(default=True)),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('last_tested_date', models.DateField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
